### ISSUE TITLE
Correccion en Index,php

### ISSUE THREAD

**Issue by Sneyder25** [Kev-1729/Grupo9_verificacion#2]
Se realizará la prueba unitaria para el login

**Comment by Kev-1729** [comment]
![Image](https://github.com/user-attachments/assets/68670cd6-4160-4a7f-9184-261ce4ba96d7)
![Image](https://github.com/user-attachments/assets/b47b3be1-2d63-4b41-8b23-14a3ca9992bd)
![Image](https://github.com/user-attachments/assets/1cdcc8c0-e343-4483-ba35-ea5599267b8c)
